#! /usr/bin/env node

const jalosi = require("./jalosi.js");
const print = console.log;
const argv = process.argv;

function usage() {
  print(`Usage: ${argv[1]} [...FILES...]`);
}

var args = argv.slice(2);
if (args.length == 0) return usage();
try {
  jalosi(args);
} catch (error) {
  console.error(error);
  print();
  return usage();
}
